export default {
    headingOneBold: 'font-bold font-spartan uppercase text-slate-900 mb-2.5 md:mb-5 text-3xl md:text-7xl',
    headingTwo: 'font-medium font-spartan uppercase text-slate-900 text-4xl md:text-5xl',
    headingTwoBoldText: 'font-bold font-spartan uppercase text-slate-900 text-4xl md:text-5xl',
    headingThreeBold: 'font-bold font-spartan text-slate-900 mb-5 text-2xl md:text-3xl',
    headingFour: 'text-3xl font-semibold font-spartan uppercase',
    headingFourBold: 'text-3xl font-bold font-spartan',
    looHeading: 'text-4xl font-semibold font-spartan uppercase',
    subHeading: 'text-slate-500 mb-5 md:mb-8 text-lg md:text-xl',
    subText: 'font-spartan text-slate-500',
    subBold: 'font-bold font-open-sans text-slate-900',
    dashboardText: 'font-spartan font-medium text-slate-900',
    paragraphText: 'font-open-sans text-sm text-slate-900',
    smallText: 'font-open-sans text-sm text-slate-500',
    tinyText: 'font-open-sans text-xs text-slate-900',
    buttonTextSm: 'font-spartan text-xs font-semibold text-slate-900',
    buttonTextLg: 'font-spartan font-bold uppercase text-slate-900',
    buttonTextMd: 'font-spartan font-semibold text-sm text-slate-900',
    looCardTitle: 'text-slate-900 font-open-sans text-sm font-semibold',
    looCardSubtext: 'text-slate-900 font-open-sans text-xs',
    looCardSmallText: 'font-open-sans text-xs text-slate-500',
    labelText: 'font-medium font-open-sans text-sm text-slate-900 ',
    errorText: 'font-open-sans text-red-800 text-xs',
    screenContainer: 'flex justify-center place-items-center min-h-screen px-5 pt-16 pb-4 my-12',
    modalContainer: 'absolute w-full h-full top-0 left-0 z-50 flex justify-center place-items-center',
    modalContentContainer: 'fixed mx-auto bg-white w-full flex flex-col min-h-[10rem] rounded-lg px-10 pt-14 pb-10 shadow font-open-sans md:w-[38rem]',
    flexCol10: 'flex flex-col gap-10',
    flexCol5: 'flex flex-col gap-5',
    flexibleCol5: 'flex flex-col gap-2.5 md:gap-5',
    flexibleCol10: 'flex flex-col gap-2.5 md:gap-10',
    flexCol2: 'flex flex-col gap-2.5 ',
    flexDirection: 'flex place-items-center gap-2.5 md:gap-5 mb-5 flex-col sm:flex-row',
    divider: 'h-[2px] bg-slate-300 mx-auto my-2.5',
    borderSlate: 'border-2 border-slate-300 rounded-lg',
    formBorder: 'bg-slate-100 p-10 rounded-lg border',
    inputField: 'bg-white h-[2.2rem] rounded-md px-2.5 border-2',
    textHover: 'hover:text-slate-700 transition-colors',
}