
export const loos = [
    {
        "id": 1,
        "name": "TEST",
        "street": "123 TEST Street",
        "region": "TEST City",
        "contact": "John TEST - 123-456-7890",
        "lat": -36.8485,
        "long": 174.7633,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'THIS IS A TEST DESCRIPTION',
    },
    {
        "id": 2,
        "name": "Harbor View Loo",
        "street": "456 Waterfront Road",
        "region": "Wellington",
        "contact": "Jane Doe - 987-654-3210",
        "lat": -41.2865,
        "long": 174.7762,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 3,
        "name": "Parkside Rest Stop",
        "street": "789 Green Park Avenue",
        "region": "Christchurch",
        "contact": "Michael Johnson - 555-123-4567",
        "lat": -43.5321,
        "long": 172.6362,
        "user_id": 2
    },
    {
        "id": 4,
        "name": "Bayfront Facilities",
        "street": "210 Ocean Drive",
        "region": "Auckland",
        "contact": "Samantha Lee - 111-222-3333",
        "lat": -36.8404,
        "long": 174.7552,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 5,
        "name": "Hillside Public Toilet",
        "street": "15 Hillcrest Lane",
        "region": "Wellington",
        "contact": "Robert White - 444-555-6666",
        "lat": -41.3095,
        "long": 174.7822,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 6,
        "name": "Riverside Comfort Zone",
        "street": "890 Riverside Avenue",
        "region": "Christchurch",
        "contact": "Elizabeth Brown - 777-888-9999",
        "lat": -43.5328,
        "long": 172.6354,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 7,
        "name": "Seaview Pit Stop",
        "street": "543 Coastal Road",
        "region": "Auckland",
        "contact": "David Williams - 321-654-9876",
        "lat": -36.8037,
        "long": 174.7549,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 8,
        "name": "Hometown Rest Area",
        "street": "987 Maple Street",
        "region": "Wellington",
        "contact": "Karen Martin - 789-654-3210",
        "lat": -41.2956,
        "long": 174.7774,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 9,
        "name": "Greenside Lavatory",
        "street": "234 Greenway Avenue",
        "region": "Christchurch",
        "contact": "Richard Wilson - 123-987-4560",
        "lat": -43.5323,
        "long": 172.6348,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 10,
        "name": "Sunset View Comfort Station",
        "street": "567 Horizon Lane",
        "region": "Auckland",
        "contact": "Lisa Turner - 777-555-1111",
        "lat": -36.7975,
        "long": 174.7446,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 11,
        "name": "Ocean Breeze Toilets",
        "street": "543 Coastal Road",
        "region": "Auckland",
        "contact": "Daniel Walker - 555-111-7777",
        "lat": -36.8002,
        "long": 174.7574,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 12,
        "name": "Riverside Rest Haven",
        "street": "210 Riverside Avenue",
        "region": "Wellington",
        "contact": "Maria Perez - 888-222-4444",
        "lat": -41.2968,
        "long": 174.7791,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 13,
        "name": "Central Park Pit Stop",
        "street": "123 Park Lane",
        "region": "Christchurch",
        "contact": "James Scott - 444-777-2222",
        "lat": -43.5296,
        "long": 172.6341,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 14,
        "name": "Beachfront Rest Spot",
        "street": "567 Sandy Beach Road",
        "region": "Auckland",
        "contact": "Sophia Carter - 222-555-8888",
        "lat": -36.8014,
        "long": 174.7437,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 15,
        "name": "Mountainside Loo",
        "street": "789 Summit Avenue",
        "region": "Wellington",
        "contact": "William Turner - 777-444-9999",
        "lat": -41.2937,
        "long": 174.7836,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 16,
        "name": "Greenview Rest Haven",
        "street": "210 Greenway Avenue",
        "region": "Christchurch",
        "contact": "Olivia Moore - 555-777-2222",
        "lat": -43.5293,
        "long": 172.6327,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 17,
        "name": "Bayfront Lavatory",
        "street": "654 Ocean Drive",
        "region": "Auckland",
        "contact": "Ethan Mitchell - 222-888-4444",
        "lat": -36.8383,
        "long": 174.7528,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 18,
        "name": "Seaview Rest Stop",
        "street": "987 Coastal Road",
        "region": "Wellington",
        "contact": "Isabella Adams - 777-222-5555",
        "lat": -41.3107,
        "long": 174.7761,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 19,
        "name": "Parkside Comfort Zone",
        "street": "123 Park Lane",
        "region": "Christchurch",
        "contact": "Liam Stewart - 444-222-7777",
        "lat": -43.5269,
        "long": 172.6335,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 20,
        "name": "Beachside Pit Stop",
        "street": "789 Sandy Beach Road",
        "region": "Auckland",
        "contact": "Mia Gray - 555-777-4444",
        "lat": -36.7992,
        "long": 174.7469,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 21,
        "name": "Hillcrest Loo",
        "street": "210 Hillcrest Lane",
        "region": "Wellington",
        "contact": "Noah Reed - 777-444-2222",
        "lat": -41.3081,
        "long": 174.7810,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 22,
        "name": "Riverfront Rest Haven",
        "street": "543 Riverside Avenue",
        "region": "Christchurch",
        "contact": "Ava Turner - 555-777-4444",
        "lat": -43.5261,
        "long": 172.6311,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 23,
        "name": "Sunrise View Loo",
        "street": "987 Horizon Lane",
        "region": "Auckland",
        "contact": "Jackson Foster - 777-222-5555",
        "lat": -36.7967,
        "long": 174.7430,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 24,
        "name": "Oceanfront Toilets",
        "street": "123 Coastal Road",
        "region": "Auckland",
        "contact": "Emma Adams - 555-222-7777",
        "lat": -36.7981,
        "long": 174.7605,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 25,
        "name": "Riverside Comfort Spot",
        "street": "210 Riverside Avenue",
        "region": "Wellington",
        "contact": "Liam Gray - 777-222-4444",
        "lat": -41.3047,
        "long": 174.7798,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 26,
        "name": "Central Park Restroom",
        "street": "543 Park Lane",
        "region": "Christchurch",
        "contact": "Olivia Smith - 555-222-7777",
        "lat": -43.5252,
        "long": 172.6285,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 27,
        "name": "Beachside Lavatory",
        "street": "789 Sandy Beach Road",
        "region": "Auckland",
        "contact": "Liam Martin - 777-222-5555",
        "lat": -36.7941,
        "long": 174.7422,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 28,
        "name": "Mountainside Rest Area",
        "street": "123 Summit Avenue",
        "region": "Wellington",
        "contact": "Emma Turner - 555-777-2222",
        "lat": -41.2939,
        "long": 174.7879,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 29,
        "name": "Greenside Loo",
        "street": "210 Greenway Avenue",
        "region": "Christchurch",
        "contact": "Noah Lee - 777-222-8888",
        "lat": -43.5226,
        "long": 172.6294,
        "user_id": 2,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 30,
        "name": "Seaview Comfort Zone",
        "street": "543 Coastal Road",
        "region": "Auckland",
        "contact": "Ava Taylor - 555-222-8888",
        "lat": -36.7955,
        "long": 174.7476,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 31,
        "name": "Riverside Pit Stop",
        "street": "789 Riverside Avenue",
        "region": "Wellington",
        "contact": "Liam Turner - 777-222-3333",
        "lat": -41.3022,
        "long": 174.7811,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 32,
        "name": "Sunset View Rest Haven",
        "street": "123 Horizon Lane",
        "region": "Christchurch",
        "contact": "Emma Scott - 555-222-1111",
        "lat": -43.5234,
        "long": 172.6263,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 33,
        "name": "City Park Lavatory",
        "street": "210 Park Lane",
        "region": "Auckland",
        "contact": "Noah Turner - 777-222-9999",
        "lat": -36.8007,
        "long": 174.7654,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 34,
        "name": "Harbor View Rest Stop",
        "street": "543 Waterfront Road",
        "region": "Wellington",
        "contact": "Ava Carter - 555-222-4444",
        "lat": -41.2945,
        "long": 174.7750,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 35,
        "name": "Parkside Loo",
        "street": "789 Park Lane",
        "region": "Christchurch",
        "contact": "Noah Walker - 777-222-6666",
        "lat": -43.5209,
        "long": 172.6269,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 36,
        "name": "Beachfront Comfort Zone",
        "street": "123 Sandy Beach Road",
        "region": "Auckland",
        "contact": "Emma Turner - 555-222-5555",
        "lat": -36.8040,
        "long": 174.7408,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 37,
        "name": "Mountainside Pit Stop",
        "street": "210 Summit Avenue",
        "region": "Wellington",
        "contact": "Noah Foster - 777-222-2222",
        "lat": -41.2972,
        "long": 174.7850,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 38,
        "name": "Greenview Rest Haven",
        "street": "543 Greenway Avenue",
        "region": "Christchurch",
        "contact": "Ava Adams - 555-222-7777",
        "lat": -43.5205,
        "long": 172.6245,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 39,
        "name": "Sunrise View Loo",
        "street": "789 Horizon Lane",
        "region": "Auckland",
        "contact": "Noah Turner - 777-222-3333",
        "lat": -36.8023,
        "long": 174.7395,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 40,
        "name": "Oceanfront Toilets",
        "street": "123 Coastal Road",
        "region": "Auckland",
        "contact": "Emma Carter - 555-222-6666",
        "lat": -36.7956,
        "long": 174.7621,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 41,
        "name": "Riverside Comfort Spot",
        "street": "210 Riverside Avenue",
        "region": "Wellington",
        "contact": "Noah Walker - 777-222-7777",
        "lat": -41.2977,
        "long": 174.7822,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 42,
        "name": "Central Park Restroom",
        "street": "543 Park Lane",
        "region": "Christchurch",
        "contact": "Ava Scott - 555-222-8888",
        "lat": -43.5187,
        "long": 172.6230,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 43,
        "name": "Beachside Lavatory",
        "street": "789 Sandy Beach Road",
        "region": "Auckland",
        "contact": "Noah Adams - 777-222-9999",
        "lat": -36.8032,
        "long": 174.7377,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 44,
        "name": "Mountainside Rest Area",
        "street": "123 Summit Avenue",
        "region": "Wellington",
        "contact": "Emma Turner - 555-222-1111",
        "lat": -41.2999,
        "long": 174.7908,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 45,
        "name": "Greenside Loo",
        "street": "210 Greenway Avenue",
        "region": "Christchurch",
        "contact": "Noah Lee - 777-222-4444",
        "lat": -43.5178,
        "long": 172.6205,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 46,
        "name": "Seaview Comfort Zone",
        "street": "543 Coastal Road",
        "region": "Auckland",
        "contact": "Ava Taylor - 555-222-7777",
        "lat": -36.7998,
        "long": 174.7529,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 47,
        "name": "Riverside Pit Stop",
        "street": "789 Riverside Avenue",
        "region": "Wellington",
        "contact": "Noah Turner - 777-222-8888",
        "lat": -41.2996,
        "long": 174.7862,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 48,
        "name": "Sunset View Rest Haven",
        "street": "123 Horizon Lane",
        "region": "Christchurch",
        "contact": "Emma Scott - 555-222-3333",
        "lat": -43.5159,
        "long": 172.6172,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 49,
        "name": "City Park Lavatory",
        "street": "210 Park Lane",
        "region": "Auckland",
        "contact": "Noah Turner - 777-222-5555",
        "lat": -36.8059,
        "long": 174.7604,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    },
    {
        "id": 50,
        "name": "Harbor View Rest Stop",
        "street": "543 Waterfront Road",
        "region": "Wellington",
        "contact": "Ava Carter - 555-222-9999",
        "lat": -41.3037,
        "long": 174.7745,
        "user_id": 1,
        "weekday": '9am - 2pm',
        "weekend": '10pm - 2pm',
        "fee": '2 dollars',
        "about": 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia ante eu elit pretium imperdiet. ' +
            'Nullam in tristique justo. In suscipit metus et nunc ornare, nec blandit eros malesuada. Praesent aliquet' +
            ' elit at nisl porta, vel lobortis dolor auctor.',
    }
]
